apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-et0q
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0012-tenant/tkrw-pr712-0075-0012-app/devfile-sample-et0q@sha256:a1da2b5952f8ba550de20d4026921c679afb3b2849f0896d4dc9410b9b404c28
        name: my-nodejs
        resources: {}
status: {}
